project:
  type: website
  output-dir: docs

website:
  title: "isabel zimmerman"
  site-url: https://isabelizimm.me/
  description: "Isabel Zimmerman's personal blog"
  twitter-card: true
  favicon: images/iz.png
  navbar:
    background: '#e6eaed'
    right:
      - file: index.qmd
        text: "about"
      - file: blog.qmd
        text: "blog"
      - file: work.qmd
        text: "work"
format:
  html:
    theme: 
      light: [light.scss]
